#!/command/with-contenv sh

set -eu

cd /mc/backend

exec /usr/local/bin/celery -A app.task.celery worker \
  --pool=gevent \
  --concurrency "${CELERY_WORKER_CONCURRENCY:-2}" \
  --prefetch-multiplier "${CELERY_WORKER_PREFETCH_MULTIPLIER:-1}" \
  --max-tasks-per-child "${CELERY_WORKER_MAX_TASKS_PER_CHILD:-500}" \
  --loglevel="${CELERY_LOG_LEVEL:-INFO}"
