#!/command/with-contenv sh

set -eu

cd /mc/backend

exec python3 -m celery -A app.task.celery flower \
  --port="${FLOWER_PORT:-8555}" \
  --url-prefix="${FLOWER_URL_PREFIX:-flower}" \
  --basic-auth="${FLOWER_BASIC_AUTH:-admin:123456}"
